name = "Eyrie Craft"
author = "Hawk_v3"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6b78fb17da2ec380a99e86382d3e1a8f39e2da98bafadffafc39ca53297fadc"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
