name = "Eyrie Craft"
author = "Hawk_v3"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2464ce844ae252d7de3f379a36902e3b1428a32ff92aeb646651896779840a6d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
