name = "Eyrie Craft"
author = "Hawk_v3"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12edce0d93a716b623e2bad42c5dd72c821bd3d636462032f53ece7bb4f4c69b"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
